### ISSUE TITLE
Server Crash: When accessing a float array with enumeration

### ISSUE THREAD

**Issue by stickz** [alliedmodders/sourcemod#800]
A sourcemod plugin I created is crashing my game-server, every-time [this line of code](https://github.com/stickz/Redstone/blob/master/addons/sourcemod/scripting/nd_damage/damage_events.sp#L275-L276) is called. Accelerator is saying there's no crash dump to upload for some reason. Here's my source-engine crash report.
```
----------------------------------------------
----------------------------------------------
CRASH: Thu Apr  5 00:36:23 CEST 2018
Start Line: ./srcds_linux -console -game nucleardawn +map hydro -maxplayers 32 -ip 94.130.188.173 -port 27070 -steamport 4391 -timeout 10 -condebug -debug
[New LWP 32112]
Core was generated by `./srcds_linux -console -game nucleardawn +map hydro -maxplayers 32 -ip 94.130.1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xf7fc2e94 in _dl_get_tls_static_info () from /lib/ld-linux.so.2
#0  0xf7fc2e94 in _dl_get_tls_static_info () from /lib/ld-linux.so.2
#1  0xf7daad04 in ?? ()
#2  0xf7fcd9d8 in ?? () from /lib/ld-linux.so.2
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
No symbol table info available.
eax            0xf7fd8000	-134381568
ecx            0xbc0	3008
edx            0xf7fcd9d8	-134424104
ebx            0xf7dc0000	-136577024
esp            0xfffbb33c	0xfffbb33c
ebp            0xf7dc0000	0xf7dc0000
esi            0x8	8
edi            0xfffbb3e8	-281624
eip            0xf7fc2e94	0xf7fc2e94 <_dl_get_tls_static_info+20>
eflags         0x10296	[ PF AF SF IF RF ]
cs             0x23	35
ss             0x2b	43
ds             0x2b	43
es             0x2b	43
fs             0x0	0
gs             0x63	99
k0             0x0	0
k1             0x0	0
k2             0x0	0
k3             0x0	0
k4             0x0	0
k5             0x0	0
k6             0x0	0
k7             0x0	0
From        To          Syms Read   Shared Object Library
                        No          bin/libm.so.6
                        No          bin/libdl.so.2
0xf7e31220  0xf7eeeeb4  Yes (*)     /usr/lib32/libstdc++.so.6
                        No          bin/libpthread.so.0
                        No          bin/libc.so.6
0xf7fb1ab0  0xf7fcc76b  Yes (*)     /lib/ld-linux.so.2
0xf7bd40b0  0xf7be97f5  Yes (*)     /usr/lib32/libgcc_s.so.1
(*): Shared library is missing debugging information.
Dump of assembler code for function _dl_get_tls_static_info:
   0xf7fc2e80 <+0>:	call   0xf7fcc74f
   0xf7fc2e85 <+5>:	add    $0x1517b,%eax
   0xf7fc2e8a <+10>:	mov    0x4(%esp),%edx
   0xf7fc2e8e <+14>:	mov    0x854(%eax),%ecx
=> 0xf7fc2e94 <+20>:	mov    %ecx,(%edx)
   0xf7fc2e96 <+22>:	mov    0x85c(%eax),%edx
   0xf7fc2e9c <+28>:	mov    0x8(%esp),%eax
   0xf7fc2ea0 <+32>:	mov    %edx,(%eax)
   0xf7fc2ea2 <+34>:	ret    
End of assembler dump.
Stack level 0, frame at 0xfffbb340:
 eip = 0xf7fc2e94 in _dl_get_tls_static_info; saved eip = 0xf7daad04
 called by frame at 0xfffbb344
 Arglist at 0xfffbb338, args: 
 Locals at 0xfffbb338, Previous frame's sp is 0xfffbb340
 Saved registers:
  eip at 0xfffbb33c
End of Source crash report
----------------------------------------------
```

**Comment by KyleSanderson** [comment]
Can you provide a minimal platform independent test case?

**Comment by asherkin** [comment]
Did you compile your own SourceMod, or are otherwise not using one of our releases?

[Please include complete version info on all issue reports.](https://github.com/alliedmodders/sourcemod/blob/master/.github/CONTRIBUTING.md#details-details-details)

**Comment by asherkin** [comment]
And please can you include what glibc version you are using on your server.

**Comment by stickz** [comment]
I was NOT able to remove the Nuclear Dawn dependency, however, I was able to produce a much smaller and more detailed test case. I am running glib 2.27 on Ubuntu 18.04 Bionic Beaver.

```
Metamod:Source version 1.10.5
Built from: https://github.com/alliedmodders/metamod-source/commit/e0ef546
Build ID: 939:e0ef546
Loaded As: Valve Server Plugin
Compiled on: May 10 2015
Plugin interface version: 15:14
SourceHook version: 5:5
http://www.metamodsource.net/

```
 ```
SourceMod Version Information:
    SourceMod Version: 1.8.0.5973
    SourcePawn Engine: SourcePawn 1.8, jit-x86 (build 1.8.0.5973)
    SourcePawn API: v1 = 4, v2 = 11
    Compiled on: Feb  9 2017 15:06:54
    Built from: https://github.com/alliedmodders/sourcemod/commit/42b281a
    Build ID: 5973:42b281a
    http://www.sourcemod.net/
```

```
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

enum multREDs 
{
	red_bunker_mult = 0,
	red_assembler_mult,
	red_transport_mult
}

ConVar gCvar_Red[multREDs];
float gFloat_Red[multREDs];

#define STRUCT_BUNKER "struct_command_bunker"

public void OnPluginStart()
{
	// Fill the ConVar array with some data
	CreateRedConVars();	
	
	// Fill the float array with some data
	UpdateConVarCache();
	
	// Hook when the round starts. Bunker entity must be available.
	HookEvent("round_start", Event_RoundStart, EventHookMode_PostNoCopy);
}

public Action Event_RoundStart(Event event, const char[] name, bool dontBroadcast)
{
	// Loop through all the entities on the server. Find the two bunker entities and hook take damage.
	int loopEntity = INVALID_ENT_REFERENCE;
	while ((loopEntity = FindEntityByClassname(loopEntity, STRUCT_BUNKER)) != INVALID_ENT_REFERENCE) {
		SDKHook(loopEntity, SDKHook_OnTakeDamage, ND_OnBunkerDamaged);		
	}
}

public Action ND_OnBunkerDamaged(int victim, int &attacker, int &inflictor, float &damage, int &damagetype) 
{
	// This does NOT trigger a server crash
	damage *= 1.2;	
	PrintToServer("Hard-coded damage value");
	
	// This does NOT trigger a server crash
	float mult = gFloat_Red[red_bunker_mult];
	damage *= mult;	
	PrintToServer("Assigned damage value to local variable");
	
	// But this WILL trigger a server crash
	damage *= gFloat_Red[red_bunker_mult];
	PrintToServer("Assigned damage value from float array");

	return Plugin_Changed;
}

void CreateRedConVars()
{
	char convarName[multREDs][] = {
		"sm_mult_bunker_red",
		"sm_mult_assembler_red",
		"sm_mult_transport_red"		
	};
	
	char convarDef[multREDs][] = { "120", "105", "150" };
	
	char convarDesc[multREDs][] = {
		"Percentage of normal damage REDs deal to the bunker",
		"Percentage of normal damage REDs deal to assemblers",
		"Percentage of normal damage REDs deal to transport gates"
	};
	
	// Use the AutoExecConfig wrapper to create the ConVars
	for (int convar = 0; convar < view_as<int>(multREDs); convar++) {
		gCvar_Red[convar] = CreateConVar(convarName[convar], convarDef[convar], convarDesc[convar]);
	}
}

void UpdateConVarCache()
{
	for (int r = 0; r < view_as<int>(multREDs); r++) {
		gFloat_Red[r] = gCvar_Red[r].FloatValue / 100.0;
	}
}
```

**Comment by KyleSanderson** [comment]
To clarify, the convars are absolutely required and this doesn't happen on any other game?

**Comment by stickz** [comment]
The ConVars are not required. Here is a small test case. I tried hooking a player entity when they took damage and it didn't register properly. This caused no server crash though. I did not investigate further.

```
#include <sourcemod>
#include <sdktools>
#include <sdkhooks>

enum multREDs 
{
	red_bunker_mult = 0,
	red_assembler_mult,
	red_transport_mult
}

float gFloat_Red[multREDs];

#define STRUCT_BUNKER "struct_command_bunker"

public void OnPluginStart()
{
	// Initialize array with value before accessing 
	gFloat_Red[red_bunker_mult] = 1.2;
	
	// Hook when the round starts. Bunker entity must be available.
	HookEvent("round_start", Event_RoundStart, EventHookMode_PostNoCopy);
}

public Action Event_RoundStart(Event event, const char[] name, bool dontBroadcast)
{
	// Loop through all the entities on the server. Find the two bunker entities and hook take damage.
	int loopEntity = INVALID_ENT_REFERENCE;
	while ((loopEntity = FindEntityByClassname(loopEntity, STRUCT_BUNKER)) != INVALID_ENT_REFERENCE) {
		SDKHook(loopEntity, SDKHook_OnTakeDamage, ND_OnBunkerDamaged);		
	}
}

public Action ND_OnBunkerDamaged(int victim, int &attacker, int &inflictor, float &damage, int &damagetype) 
{
	// This does NOT trigger a server crash
	damage *= 1.2;	
	PrintToServer("Hard-coded damage value");
	
	// This does NOT trigger a server crash
	float mult = gFloat_Red[red_bunker_mult];
	damage *= mult;	
	PrintToServer("Assigned damage value to local variable");
	
	// But this WILL trigger a server crash
	damage *= gFloat_Red[red_bunker_mult];
	PrintToServer("Assigned damage value from float array");

	return Plugin_Changed;
}
```

**Comment by Fyren** [comment]
When Kyle mentioned "minimal test case" he meant something like just multiplying using the array in OnPluginStart (or similar).  Whether or not that crashes, saying so is useful.  Depending on having players or SDKHooks seems extremely unlikely to be related.

**Comment by stickz** [comment]
I am unable to resimulate the server crash by performing these actions OnPluginStart(). SDK_Hooks is absolutely required. I have some new observations by testing though.

1.  If I multiply the damage by 0.0 first, it doesn't not crash the server.
2. Performing these actions OnPluginStart() will return 0.0 for the damage instead of 1.2. Unless the access being accessed is assigned to a variable first, before performing the multiplication operation.
3. Ether of these lines will crash the server because array access is related.
`damage *= gFloat_Red[red_bunker_mult];`
`PrintToServer("The damage value is %f", gFloat_Red[red_bunker_mult]);`

**Comment by stickz** [comment]
Also, I'm using stock builds of sourcemod and metamod. I though the version info clarified that.
